### ISSUE TITLE
ios18, a bug 

### ISSUE THREAD

**Issue by Yumega** [iamrbn/Inline-Weather#1]
>> SCRIPT IS UP TO DATE!
Error on line 243:26: TypeError: undefined is not an object (evaluating 'datas.daily.length')

**Comment by iamrbn** [comment]
@Yumega Which script version do you use?

**Comment by Yumega** [comment]
> @Yumega Which script version do you use?

where to check the script version? ios18 beta

**Comment by iamrbn** [comment]
I don't receive any errors, but i also use the current iOS version (_17.5.1_)
Can you please post a screenshot of line 211 to 244?

**Comment by Yumega** [comment]
sorry I deleted it yesterday, no need it
